package com.pointlion.sys.mvc.common.model.base;


import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.activerecord.Model;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseSysPost<M extends BaseSysPost<M>> extends Model<M> implements IBean {
	
	public void setId(java.lang.String id) {
		set("id", id);
	}

	public java.lang.String getId() {
		return get("id");
	}

	public void setName(java.lang.String name) {
		set("name", name);
	}

	public java.lang.String getName() {
		return get("name");
	}

	public void setCreateTime(java.lang.String createTime) {
		set("create_time", createTime);
	}

	public java.lang.String getCreateTime() {
		return get("create_time");
	}

	
	public void setCreateuser(java.lang.String createUser) {
		set("create_user", createUser);
	}

	public java.lang.String getCreateUser() {
		return get("create_user");
	}

	public void setRankid(java.lang.String rankid) {
		set("rankid", rankid);
	}

	public java.lang.String getRankid() {
		return get("rankid");
	}
	
	public void setOrgid(java.lang.String orgid) {
		set("orgid", orgid);
	}

	public java.lang.String getOrgid() {
		return get("orgid");
	}
	
	public void setSort(java.lang.Integer sort) {
		set("sort", sort);
	}

	public java.lang.Integer getSort() {
		return get("sort");
	}

}
