package com.pointlion.sys.mvc.common.model;

import java.util.ArrayList;
import java.util.List;

import com.jfinal.aop.Before;
import com.jfinal.kit.StrKit;
import com.jfinal.plugin.activerecord.Db;
import com.jfinal.plugin.activerecord.Page;
import com.jfinal.plugin.activerecord.Record;
import com.jfinal.plugin.activerecord.tx.Tx;
import com.pointlion.sys.mvc.common.dto.ZtreeNode;
import com.pointlion.sys.mvc.common.model.base.BaseSysOrg;
import com.pointlion.sys.mvc.common.model.base.BaseSysPost;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SysPost extends BaseSysPost<SysPost> {
	public static final SysPost dao = new SysPost();
	
	/***
	 * 根据主键查询
	 */
	public SysPost getById(String id){
		return SysPost.dao.findById(id);
	}
	/***
	 * 删除
	 * @param ids
	 */
	@Before(Tx.class)
	public void deleteByIds(String ids){
    	String idarr[] = ids.split(",");
    	for(String id : idarr){
    		SysPost o = SysPost.dao.getById(id);
    		o.delete();
    	}
	}
	
	/***
	 * 分页查询
	 * @param id
	 * @return
	 */
	public Page<Record> getPageByOrgid(int pnum,int psize,String orgid){
		String sql = "from sys_post p left join sys_rank r on r.id=p.rankid left join sys_user u on u.id=p.create_user ";
		if(StrKit.notBlank(orgid)){
			sql = sql + " where p.orgid='"+orgid+"' ";
		}
		sql = sql + " order by p.sort ";
		return Db.paginate(pnum, psize, "select p.*,r.`name` rankName,u.`name` userName", sql);
	}
	
}
